apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: relliott57myrepo
  description: My new application
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/workshop_users
  lifecycle: experimental
